language: r
sudo: required
cache: packages

r:
  - release
  - devel

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dependencies = TRUE)'

script:
  - R CMD build .
  - R CMD check *tar.gz